# Generated by Django 4.1.3 on 2023-05-23 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mrsachin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.CharField(max_length=12)),
                ('hobby', models.CharField(max_length=50)),
                ('familyno', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sibling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brothername', models.CharField(max_length=50)),
                ('sistername', models.CharField(max_length=50)),
                ('mrsachin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mrsachin')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathername', models.CharField(max_length=50)),
                ('mothername', models.CharField(max_length=50)),
                ('mrsachin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mrsachin')),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.ImageField(blank=True, default='cv', height_field='cv_height', max_length=255, null=True, upload_to='cv', width_field='cv_width')),
                ('cv_height', models.PositiveIntegerField(blank=True, null=True)),
                ('cv_width', models.PositiveIntegerField(blank=True, null=True)),
                ('mrsachin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.mrsachin')),
            ],
        ),
    ]
