# Generated by Django 4.1.3 on 2023-05-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='cv',
            field=models.ImageField(blank=True, height_field='cv_height', max_length=255, null=True, upload_to='cv', width_field='cv_width'),
        ),
    ]
